fields:
              # --- DEFINISI FIELD UNTUK SATU GAME ---
              - label: "Judul"
                name: "title"
                widget: "string"
                required: true
              
              # --- FIELD UKURAN BARU ---
              - label: "Ukuran Full Version (GB)"
                name: "size_full"
                widget: "number"
                step: 0.1
                required: true # Wajib diisi

              - label: "Ukuran RIP/Compressed (GB)"
                name: "size_rip"
                widget: "number"
                step: 0.1
                required: false # Boleh kosong
              # --- END UKURAN BARU ---

              - label: "Bahasa"
                name: "language"
                widget: "string"
              - label: "Genre/Tagging"
                name: "genre"
                widget: "string"
              - label: "Deskripsi"
                name: "description"
                widget: "text"
              - label: "Gambar Cover"
                name: "coverImage"
                widget: "image"
                required: false
              - label: "Screenshots Gameplay"
                name: "screenshots"
                widget: "list"
                field:
                  label: "Screenshot"
                  name: "screenshot_image"
                  widget: "image"
