backend:
  name: github
  repo: Kharui/Kharui-Store # Pastikan ini sesuai dengan nama repositori Anda
  branch: main
  client_id: Ov23liAfQyI9r84TZfOE # Client ID Anda
  
  # SOLUSI LOGIN LOOP: Tentukan URL otentikasi secara eksplisit
  base_url: https://api.github.com
  auth_url: https://kharui-store.pages.dev/auth/ # URL callback Decap CMS
  
media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: 'games' 
    label: 'Katalog Game'
    files:
      - file: 'games.json' 
        label: 'Daftar Game'
        name: 'game_data'
        fields:
          - label: "Daftar Game"
            name: "entries"
            widget: "list"
            allow_add: true 
            fields:
              - label: "Judul"
                name: "title"
                widget: "string"
                required: true
              
              # Field Ukuran Baru (Full Version)
              - label: "Ukuran Full Version (GB)"
                name: "size_full"
                widget: "number"
                step: 0.1
                required: true 

              # Field Ukuran Baru (RIP/Compressed)
              - label: "Ukuran RIP/Compressed (GB)"
                name: "size_rip"
                widget: "number"
                step: 0.1
                required: false

              - label: "Bahasa"
                name: "language"
                widget: "string"
              - label: "Genre/Tagging"
                name: "genre"
                widget: "string"
              - label: "Deskripsi"
                name: "description"
                widget: "text"
              - label: "Gambar Cover"
                name: "coverImage"
                widget: "image"
                required: false
              - label: "Screenshots Gameplay"
                name: "screenshots"
                widget: "list"
                field:
                  label: "Screenshot"
                  name: "screenshot_image"
                  widget: "image"
